#!/usr/bin/env bash
# Set up a Yocto scarthgap build for the usb-proxy appliance (Orange Pi Zero).
#
# Clones the required layers at the scarthgap branch onto the native Linux
# filesystem (NOT the macOS-shared mount) and writes build/conf/{bblayers,local}.
# Re-runnable: existing clones are left alone.
#
# Run inside the OrbStack Debian machine, e.g.:
#   orb run bash /Users/<you>/Downloads/meta-usbproxy/scripts/setup-build.sh
#
# Then:
#   cd ~/yocto/usbproxy && source layers/poky/oe-init-build-env build
#   bitbake usbproxy-image
set -euo pipefail

# This layer (the repo this script lives in), as seen inside the container.
LAYER_USBPROXY="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Everything heavy lives on the container's native fs for speed/correctness.
WORK="${YOCTO_WORK:-$HOME/yocto/usbproxy}"
LAYERS="$WORK/layers"
BRANCH="scarthgap"

mkdir -p "$LAYERS"

clone() {  # clone <dir> <url>
    local dir="$LAYERS/$1" url="$2"
    if [ -d "$dir/.git" ]; then
        echo ">> $1 already present, skipping"
    else
        echo ">> cloning $1 ($BRANCH)"
        git clone --depth 1 -b "$BRANCH" "$url" "$dir"
    fi
}

clone poky               https://git.yoctoproject.org/poky
clone meta-openembedded  https://git.openembedded.org/meta-openembedded
clone meta-arm           https://git.yoctoproject.org/meta-arm
clone meta-sunxi         https://github.com/linux-sunxi/meta-sunxi

# Initialise the build dir (creates conf/ if absent). oe-init-build-env trips
# over `set -u` (it reads unset vars like BBSERVER), so relax it just here.
cd "$WORK"
set +u
# shellcheck disable=SC1091
source "$LAYERS/poky/oe-init-build-env" "$WORK/build" >/dev/null
set -u

CONF="$WORK/build/conf"

cat > "$CONF/bblayers.conf" <<EOF
# Auto-generated by meta-usbproxy/scripts/setup-build.sh
POKY_BBLAYERS_CONF_VERSION = "2"
BBPATH = "\${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \\
  $LAYERS/poky/meta \\
  $LAYERS/poky/meta-poky \\
  $LAYERS/meta-openembedded/meta-oe \\
  $LAYERS/meta-openembedded/meta-python \\
  $LAYERS/meta-arm/meta-arm \\
  $LAYERS/meta-arm/meta-arm-toolchain \\
  $LAYERS/meta-sunxi \\
  $LAYER_USBPROXY \\
  "
EOF

cat > "$CONF/local.conf" <<EOF
# Auto-generated by meta-usbproxy/scripts/setup-build.sh
MACHINE = "orange-pi-zero"
DISTRO  = "usbproxy"

# Keep big build state on the native fs (this WORK dir lives on it).
DL_DIR     = "$WORK/downloads"
SSTATE_DIR = "$WORK/sstate-cache"
TMPDIR     = "$WORK/tmp"

# Build parallelism (10-core / 15 GiB OrbStack VM).
BB_NUMBER_THREADS = "8"
PARALLEL_MAKE = "-j 8"

# Appliance output: flashable SD image.
IMAGE_FSTYPES = "wic.gz wic.bmap"

# Bundle the appliance root filesystem into the kernel as an initramfs (runs
# from RAM; no rootfs partition). Build target is usbproxy-image (the SD image).
INITRAMFS_IMAGE = "usbproxy-initramfs"
INITRAMFS_IMAGE_BUNDLE = "1"

# No package manager, no SDK machine bloat.
PACKAGE_CLASSES = "package_ipk"
USER_CLASSES ?= "buildstats"
CONF_VERSION = "2"

# Accept meta-sunxi's GPU/firmware licences if pulled in transitively.
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"
EOF

echo
echo "Setup complete."
echo "  build dir : $WORK/build"
echo "  layer     : $LAYER_USBPROXY"
echo
echo "Next:"
echo "  cd $WORK && source layers/poky/oe-init-build-env build"
echo "  bitbake usbproxy-image"
