# /etc/inittab is generated by the busybox-inittab recipe: it installs
# file://inittab, then appends a serial getty per SERIAL_CONSOLES. We replace
# the template file (files/inittab) so usb-proxy is forked as soon as proc,
# sysfs and devtmpfs are mounted, with power-tune and the pstore mount run as
# `once` entries alongside it instead of `sysinit` entries ahead of it. The
# ttyS0 recovery getty is still appended by the recipe.
FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

# Headless appliance: no virtual-terminal (tty1) getty. The serial getty on
# ttyS0 (from SERIAL_CONSOLES) is kept for recovery.
USE_VT = "0"
