# /etc/inittab is generated by the busybox-inittab recipe (it copies a base
# template, then appends a serial getty per SERIAL_CONSOLES). We append the
# appliance's own respawn entry here, after that generation runs — so the
# read-only-rootfs sysinit lines and the ttyS0 recovery getty are preserved and
# we only add what we need.

# Headless appliance: no virtual-terminal (tty1) getty. The serial getty on
# ttyS0 (from SERIAL_CONSOLES) is kept for recovery.
USE_VT = "0"

do_install:append() {
    printf '\n# Appliance power tuning (offline spare CPU cores), run once at boot.\n' >> ${D}${sysconfdir}/inittab
    printf '::sysinit:/usr/bin/power-tune\n' >> ${D}${sysconfdir}/inittab
    printf '\n# Crash post-mortem: expose ramoops records (the kernel auto-reboots on\n' >> ${D}${sysconfdir}/inittab
    printf '# any oops/panic; the crash text lands here, surviving the reboot).\n' >> ${D}${sysconfdir}/inittab
    printf '::sysinit:/bin/mount -t pstore pstore /sys/fs/pstore\n' >> ${D}${sysconfdir}/inittab
    printf '\n# Feed the hardware watchdog (armed by U-Boot at power-on; a silent hang\n' >> ${D}${sysconfdir}/inittab
    printf '# anywhere resets the board in <=8s). -F: foreground so init tracks it.\n' >> ${D}${sysconfdir}/inittab
    printf '::respawn:/sbin/watchdog -F -T 8 -t 2 /dev/watchdog\n' >> ${D}${sysconfdir}/inittab
    printf '\n# usb-proxy appliance: the single purpose of this device.\n' >> ${D}${sysconfdir}/inittab
    printf '# Respawn on exit covers device unplug/replug and crashes.\n' >> ${D}${sysconfdir}/inittab
    printf '::respawn:/usr/bin/usb-proxy-run\n' >> ${D}${sysconfdir}/inittab
}
